import os
import requests
from dotenv import load_dotenv

load_dotenv()

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")
GITLAB_PROJECT_ID = os.getenv("GITLAB_PROJECT_ID")
GITLAB_API_BASE = "https://gitlab.com/api/v4"

def prepare_gitlab_action(
    task_type,
    dataset,
    quality_result,
    fivetran_status=None,
    support_result=None,
    transformation=None,
    messages=None,
    agent_summary=None
):
    title = f"{task_type}: Review required for {dataset}"

    lines = [
        "# PipelinePilot AI Generated Action",
        "",
        f"**Task Type:** {task_type}",
        f"**Dataset:** {dataset}",
        f"**Readiness Score:** {quality_result['score']}/100",
        f"**Status:** {quality_result['status']}",
    ]

    if agent_summary:
        lines.extend([
            "",
            "## Gemini Agent Summary",
            agent_summary.get("summary", "Summary not available")
        ])

    lines.extend([
        "",
        "## Fivetran Pipeline Status"
    ])

    if fivetran_status:
        lines.extend([
            f"- Connector: {fivetran_status.get('connector')}",
            f"- Status: {fivetran_status.get('status')}",
            f"- Last Sync: {fivetran_status.get('last_sync')}",
            f"- Schema Drift: {fivetran_status.get('schema_drift')}",
        ])

        new_fields = fivetran_status.get("new_fields", [])
        if new_fields:
            lines.append("- New Fields Detected:")
            for field in new_fields:
                lines.append(f"  - {field}")
    else:
        lines.append("- Fivetran status not available")

    lines.extend([
        "",
        "## Data Quality Issues"
    ])

    if quality_result.get("issues"):
        for issue in quality_result.get("issues", []):
            lines.append(f"- {issue}")
    else:
        lines.append("- No data quality issues found")

    lines.extend([
        "",
        "## Recommended Safe Fixes"
    ])

    for fix in quality_result.get("safe_fixes", []):
        lines.append(f"- {fix}")

    if support_result:
        lines.extend([
            "",
            "## Production Support Finding",
            f"- Root Cause: {support_result['root_cause']}",
            f"- Impact: {support_result['impact']}",
            f"- Recommended Fix: {support_result['recommended_fix']}",
        ])

    if transformation:
        lines.extend([
            "",
            "## Generated Transformation SQL",
            "```sql",
            transformation["sql"],
            "```"
        ])

    if messages:
        lines.extend([
            "",
            "## Agent Execution Summary"
        ])

        for msg in messages:
            lines.append(f"- **{msg.get('actor')}**: {msg.get('message')}")

    lines.extend([
        "",
        "---",
        "Generated by PipelinePilot AI after human approval."
    ])

    return {
        "title": title,
        "description": "\n".join(lines),
        "status": "Prepared - waiting for human approval",
        "gitlab_url": None
    }

def create_gitlab_issue(title, description):
    if not GITLAB_TOKEN:
        raise ValueError("GITLAB_TOKEN is missing in .env")

    if not GITLAB_PROJECT_ID:
        raise ValueError("GITLAB_PROJECT_ID is missing in .env")

    url = f"{GITLAB_API_BASE}/projects/{GITLAB_PROJECT_ID}/issues"

    headers = {
        "PRIVATE-TOKEN": GITLAB_TOKEN
    }

    payload = {
        "title": title,
        "description": description,
        "labels": "pipelinepilot-ai,dataops,agent-generated"
    }

    response = requests.post(url, headers=headers, data=payload, timeout=30)

    if response.status_code not in [200, 201]:
        raise Exception(f"GitLab issue creation failed: {response.status_code} - {response.text}")

    issue = response.json()

    return {
        "issue_id": issue.get("iid"),
        "web_url": issue.get("web_url"),
        "title": issue.get("title")
    }